services:
  twitchbot:
    build: .
    container_name: twitch-bot
    restart: always
    env_file: ./.env

  reminderbot:
    build: ./reminderbot
    container_name: reminder-bot
    restart: always
    env_file: ./reminderbot/.env